{"uuid": "e20d53d5-3a1a-4d01-95b2-f30c4cc820a6", "children": ["86dd1fb1-0ddc-4982-8dc3-4b289ba9ae4a", "ed8aeda6-6861-4799-8644-ab00734a912b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python36\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python36\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python36\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Project\\noc_ui_auto\\testcase\\conftest.py\", line 47, in driver\n    search_sn_and_click(driver, conf.except_sn, \"online\", 3)\n  File \"C:\\Project\\noc_ui_auto\\common\\user_public_fun.py\", line 22, in search_sn_and_click\n    EC.element_to_be_clickable((By.XPATH, UserPublicLocators.sn_input))).click()\n  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python36\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1699174583957, "stop": 1699174616069}], "start": 1699174583957, "stop": 1699174616111}